<!-- Report Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('report_type', 'Report Type:') !!}
    {!! Form::text('report_type', null, ['class' => 'form-control', 'maxlength' => 100, 'maxlength' => 100]) !!}
</div>

<!-- Generated By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('generated_by', 'Generated By:') !!}
    {!! Form::text('generated_by', null, ['class' => 'form-control', 'maxlength' => 50, 'maxlength' => 50]) !!}
</div>

<!-- Start Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('start_date', 'Start Date:') !!}
    {!! Form::text('start_date', null, ['class' => 'form-control','id'=>'start_date']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#start_date').datepicker()
    </script>
@endpush

<!-- Summary Field -->
<div class="form-group col-sm-6">
    {!! Form::label('summary', 'Summary:') !!}
    {!! Form::text('summary', null, ['class' => 'form-control', 'maxlength' => 600, 'maxlength' => 600]) !!}
</div>

<!-- Total Borrows Returned Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_borrows_returned', 'Total Borrows Returned:') !!}
    {!! Form::text('total_borrows_returned', null, ['class' => 'form-control', 'maxlength' => 20, 'maxlength' => 20]) !!}
</div>

<!-- Total Books Borrowed Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_books_borrowed', 'Total Books Borrowed:') !!}
    {!! Form::text('total_books_borrowed', null, ['class' => 'form-control', 'maxlength' => 20, 'maxlength' => 20]) !!}
</div>

<!-- Total Fines Collected Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_fines_collected', 'Total Fines Collected:') !!}
    {!! Form::text('total_fines_collected', null, ['class' => 'form-control', 'maxlength' => 20, 'maxlength' => 20]) !!}
</div>

<!-- End Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('end_date', 'End Date:') !!}
    {!! Form::text('end_date', null, ['class' => 'form-control','id'=>'end_date']) !!}
</div>

@push('page_scripts')
    <script type="text/javascript">
        $('#end_date').datepicker()
    </script>
@endpush

<!-- Most Borrowed Book Field -->
<div class="form-group col-sm-6">
    {!! Form::label('most_borrowed book', 'Most Borrowed Book:') !!}
    {!! Form::number('most_borrowed book', null, ['class' => 'form-control']) !!}
</div>

<!-- Report Data Field -->
<div class="form-group col-sm-6">
    {!! Form::label('report_data', 'Report Data:') !!}
    {!! Form::text('report_data', null, ['class' => 'form-control', 'maxlength' => 600, 'maxlength' => 600]) !!}
</div>