<!-- Report Type Field -->
<div class="col-sm-12">
    {!! Form::label('report_type', 'Report Type:') !!}
    <p>{{ $report->report_type }}</p>
</div>

<!-- Generated By Field -->
<div class="col-sm-12">
    {!! Form::label('generated_by', 'Generated By:') !!}
    <p>{{ $report->generated_by }}</p>
</div>

<!-- Start Date Field -->
<div class="col-sm-12">
    {!! Form::label('start_date', 'Start Date:') !!}
    <p>{{ $report->start_date }}</p>
</div>

<!-- Summary Field -->
<div class="col-sm-12">
    {!! Form::label('summary', 'Summary:') !!}
    <p>{{ $report->summary }}</p>
</div>

<!-- Total Borrows Returned Field -->
<div class="col-sm-12">
    {!! Form::label('total_borrows_returned', 'Total Borrows Returned:') !!}
    <p>{{ $report->total_borrows_returned }}</p>
</div>

<!-- Total Books Borrowed Field -->
<div class="col-sm-12">
    {!! Form::label('total_books_borrowed', 'Total Books Borrowed:') !!}
    <p>{{ $report->total_books_borrowed }}</p>
</div>

<!-- Total Fines Collected Field -->
<div class="col-sm-12">
    {!! Form::label('total_fines_collected', 'Total Fines Collected:') !!}
    <p>{{ $report->total_fines_collected }}</p>
</div>

<!-- End Date Field -->
<div class="col-sm-12">
    {!! Form::label('end_date', 'End Date:') !!}
    <p>{{ $report->end_date }}</p>
</div>

<!-- Most Borrowed Book Field -->
<div class="col-sm-12">
    {!! Form::label('most_borrowed book', 'Most Borrowed Book:') !!}
    <p>{{ $report->most_borrowed book }}</p>
</div>

<!-- Report Data Field -->
<div class="col-sm-12">
    {!! Form::label('report_data', 'Report Data:') !!}
    <p>{{ $report->report_data }}</p>
</div>

