<div class="card-body p-0">
    <div class="table-responsive">
        <table class="table" id="reports-table">
            <thead>
            <tr>
                <th>Report Type</th>
                <th>Generated By</th>
                <th>Start Date</th>
                <th>Summary</th>
                <th>Total Borrows Returned</th>
                <th>Total Books Borrowed</th>
                <th>Total Fines Collected</th>
                <th>End Date</th>
                <th>Most Borrowed Book</th>
                <th>Report Data</th>
                <th colspan="3">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($reports as $report)
                <tr>
                    <td>{{ $report->report_type }}</td>
                    <td>{{ $report->generated_by }}</td>
                    <td>{{ $report->start_date }}</td>
                    <td>{{ $report->summary }}</td>
                    <td>{{ $report->total_borrows_returned }}</td>
                    <td>{{ $report->total_books_borrowed }}</td>
                    <td>{{ $report->total_fines_collected }}</td>
                    <td>{{ $report->end_date }}</td>
                    <td>{{ $report->most_borrowed_book }}</td>
                    <td>{{ $report->report_data }}</td>
                    <td  style="width: 120px">
                        {!! Form::open(['route' => ['reports.destroy', $report->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            <a href="{{ route('reports.show', [$report->id]) }}"
                               class='btn btn-default btn-xs'>
                                <i class="far fa-eye"></i>
                            </a>
                            <a href="{{ route('reports.edit', [$report->id]) }}"
                               class='btn btn-default btn-xs'>
                                <i class="far fa-edit"></i>
                            </a>
                            {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="card-footer clearfix">
        <div class="float-right">
            @include('adminlte-templates::common.paginate', ['records' => $reports])
        </div>
    </div>
</div>
